import { c, s } from "../design.js";
import { Ref, DQ, TryIt, SectionBadge } from "../components/Shared.jsx";

export default function LiberalPage() {
  return (
    <div>
      <SectionBadge id="liberal" />
      <h2 style={s.h2}>What This Means for a Liberal Arts Education</h2>
      <p style={s.p}>The core of liberal arts education is precisely what AI cannot do today: interpretation, original theoretical argument, ethical reasoning that accepts responsibility for its conclusions, aesthetic judgment grounded in genuine experience. These aren't activities AI handles adequately for now. They require a self that has something at stake.</p>
      <p style={s.p}>The threatened middle is real. Mechanical writing, basic research summaries, rote analysis — AI handles these adequately. But the deliverable was never the point of assigning them. The development of a mind capable of more was the point. AI makes that distinction urgent in a way it wasn't before.</p>
      <p style={s.p}>If a student uses AI to produce an argument, the student does not have the argument. They have a document that has imitated someone else's already-made argument. But if this is so trivial to generate, what ought students be doing instead? And crucially, if AI advances well beyond its current capabilities — if AI becomes superior to humans, even — what ought humans to do? Today, liberal arts is safe, and indeed more valuable than ever before. Judgment and taste remain a distinctly human domain, best cultivated by the liberal arts. We should re-evaluate education in light of AI's capabilities to augment human reason, but we also need to confront the possibility of AI surpassing humans in these particular ways.</p>
      <div style={s.pq}>The liberal arts has always been the discipline of the gap between what can be said and what is true. AI doesn't make that tradition obsolete. Whether AI can ever close that gap is precisely the question — and it's one the liberal arts is better equipped to ask than any other field.</div>
      <div style={s.note}><span style={s.noteLabel}>Go Deeper</span><Ref label="The Atlantic: The End of the Essay" url="https://www.theatlantic.com/technology/archive/2022/12/chatgpt-ai-writing-college-student-essays/672371/" />{" · "}<Ref label="Stanford HAI: AI and Teaching" url="https://hai.stanford.edu/news/ai-will-transform-teaching-and-learning-lets-get-it-right" /></div>
      <h3 style={s.h3}>The Social and Political Dimension</h3>
      <p style={s.p}>The humanities have always been partly concerned with how societies organize themselves, distribute power, and hold institutions accountable. AI doesn't exempt those questions — it intensifies them. Educators preparing students to think clearly about the world need to prepare them for a world where the economic consequences of AI are also political consequences.</p>
      <p style={s.p}>Large-scale labor disruption has historically produced political instability. When the economic floor shifts — when whole categories of work that people built identities and communities around disappear — the social consequences follow: rising inequality, political polarization, the search for someone to blame, and weakened trust in the institutions that failed to anticipate or buffer the change. None of this requires a doomer scenario. The Displacement future, the most modest of the five, is sufficient to produce significant social stress.</p>
      <p style={s.p}>The political consequences of AI concentration are distinct and arguably more acute. If the productivity gains from AI accrue primarily to the companies and individuals who control the technology, the result is a wealth and power asymmetry unlike anything prior industrialization produced — because prior industrialization still needed large numbers of workers. An economy where a small number of AI-enabled actors can outcompete everyone else without needing their labor is an economy that strains every assumption embedded in democratic governance: that political power should roughly track the distribution of people, that labor gives workers standing to negotiate, that markets discipline power through competition.</p>
      <p style={s.p}>These are political philosophy questions. They are also economics questions, history questions, and ethics questions. They are, in other words, exactly the questions a liberal arts education is built to engage. The most important contribution educators can make right now may not be designing new AI policies for the classroom. It may be helping students recognize that they are already living inside a political transition of historic proportions — and giving them the tools to reason about it clearly rather than just react to it.</p>
      <DQ questions={["What is a liberal arts education actually for? Has your answer changed in light of AI?", "If AI-driven productivity gains concentrate among a small number of actors, what political mechanisms exist to redistribute them — and are those mechanisms adequate?", "The section argues that large-scale economic disruption becomes political disruption. What historical examples support this? Where does the analogy break down?", "What would a social contract designed for an AI economy have to assume that the current one does not?", "Aesthetic judgment — the capacity to say 'this is good and this is not, and here is why' — is one of the capabilities AI handles least well. Is that a permanent condition? And what would be lost to us if it weren't?", "If AI eventually produces work that critics and audiences agree is beautiful, what does that imply about where beauty lives — in the maker, or in the made thing? And what does your answer imply for how we should teach the humanities?", "A student submits a thoughtful, well-edited AI-generated paper. Another submits a clumsy, genuine attempt at the same argument. Which has gotten more from the assignment? Which has gotten more from their education?", "Where in your own field is the gap between 'having a document' and 'having an argument' most important — and is that gap itself at risk?"]} />
      <TryIt prompts={["Ask an AI to write the strongest possible argument that liberal arts education is obsolete in an AI-capable world. Then ask it to write the strongest argument for its continued relevance. Compare the quality and depth of both — and ask yourself which it produced more convincingly.", "Tell an AI your field, your students' likely career paths, and what you teach. Ask: 'Which parts of what I teach are most important to preserve in an AI-abundant world, and which should I reconceive entirely? Be direct and specific, not reassuring.'", "Ask an AI to design a single assignment for a college humanities course that it cannot meaningfully complete, but that requires students to use AI in the process. Evaluate whether what it proposes actually works — and whether it would have passed itself."]} />
    </div>
  );
}
