import { c, s } from "../design.js";
import { Ref, Video, DQ, TryIt, SectionBadge } from "../components/Shared.jsx";

export default function LiberalPage() {
  return (
    <div>
      <SectionBadge id="liberal" />
      <h1 style={s.h2}>What This Means for a Liberal Arts Education</h1>
      <p style={s.p}>The core of liberal arts education is precisely what AI cannot do today: interpretation, original theoretical argument, ethical reasoning that accepts responsibility for its conclusions, aesthetic judgment grounded in lived experience. These aren't activities AI handles adequately for now. They require a self with something personal on the line.</p>
      <p style={s.p}>The threatened middle is real. Mechanical writing, basic research summaries, rote analysis — AI handles these adequately. But the deliverable was never the point of assigning them. The development of a mind capable of more was the point. AI makes that distinction urgent in a way it wasn't before.</p>
      <p style={s.p}>If a student uses AI to produce an argument, the student does not have the argument. They have a document that has imitated someone else's already-made argument. But if this is so trivial to generate, what ought students be doing instead? And crucially, if AI advances well beyond its current capabilities — if AI becomes superior to humans, even — what ought humans to do? Today, judgment and taste remain a distinctly human domain, best cultivated by the liberal arts. We should re-evaluate education in light of AI's capabilities to augment human reason, but we also need to confront the possibility of AI surpassing humans in these particular ways.</p>
      <div style={s.pq}>The liberal arts has always been the discipline of the gap between what can be said and what is true. AI doesn't make that tradition obsolete. Whether AI can ever close that gap is precisely the question — and it's one the liberal arts is better equipped to ask than any other field.</div>
      <div style={s.note}><span style={s.noteLabel}>Go Deeper</span><Ref label="The Atlantic: The End of the Essay" url="https://www.theatlantic.com/technology/archive/2022/12/chatgpt-ai-writing-college-student-essays/672371/" />{" · "}<Ref label="Stanford HAI: AI and Teaching" url="https://hai.stanford.edu/news/ai-will-transform-teaching-and-learning-lets-get-it-right" /></div>

      <h3 style={s.h3}>The Argument Against This Argument</h3>
      <p style={s.p}>Everything in this section was written by people with a stake in the conclusion. The site is for liberal arts educators and their students. The site argues that liberal arts education is well placed to engage AI. That is convenient. The claim should be tested, not taken on faith.</p>
      <p style={s.p}>The strongest version of the case against: judgment and taste, while currently distinctly human, are themselves built out of pattern recognition over enormous quantities of past instances. There is no principled reason a system that has seen far more art, argument, and ethical reasoning than any single human cannot eventually do those things competently. The intuition that judgment is permanently human may be the same intuition every prior generation had about whatever capacity got automated next. Chess masters thought intuitive position evaluation was permanently human until 1997. Radiologists thought diagnostic pattern recognition was permanently human until the 2020s. Philosophers may be making the same bet about reasoning.</p>
      <p style={s.p}>The direct response to that argument is not to dismiss it. It is to notice that liberal arts education has never depended only on the claim that its outputs are uniquely human. It has depended on the claim that the <em>practice</em> of forming a judgment changes the person who forms it. Even if an AI eventually produces a better essay on Kant than any student in the room, the student who wrote a worse one has done something the AI did not: they have become someone capable of being changed by Kant. Whether that distinction holds — whether being changed is itself a thing AI can simulate or a thing only a person with something on the line can undergo — is a question the liberal arts is built to ask, but it is not a question the liberal arts has already answered in its own favor.</p>

      <h3 style={s.h3}>What Educators Can Actually Do</h3>
      <Video id="8FnOkxj0ZuA" caption="Ethan Mollick: Co-Intelligence in the Classroom — the homework apocalypse, and why experimentation beats prohibition." />
      <p style={s.p}>The most important contribution educators can make right now is not designing new AI policies for the classroom. It is restructuring the work students do so that what is being practiced cannot be done by the AI even if the AI does the deliverable. Some concrete moves:</p>
      <ul style={{ listStyle: "none", padding: 0, marginBottom: "16px" }}>
        <li style={{ padding: "5px 0 5px 22px", position: "relative", marginBottom: "4px" }}><span style={{ position: "absolute", left: 0, color: c.primary }}>–</span>Assignments that require students to defend a position out loud, to questions they couldn't anticipate. AI can write the paper. It cannot sit in the room.</li>
        <li style={{ padding: "5px 0 5px 22px", position: "relative", marginBottom: "4px" }}><span style={{ position: "absolute", left: 0, color: c.primary }}>–</span>Reading that is annotated in class, by hand, with attention to specific passages — the practice of close reading itself, not the production of a reading.</li>
        <li style={{ padding: "5px 0 5px 22px", position: "relative", marginBottom: "4px" }}><span style={{ position: "absolute", left: 0, color: c.primary }}>–</span>Writing in stages: thesis, AI-assisted draft, then a final pass in which the student must mark every sentence as "mine," "AI's that I endorse," or "AI's that I reject and rewrote" — making the cognitive work visible.</li>
        <li style={{ padding: "5px 0 5px 22px", position: "relative", marginBottom: "4px" }}><span style={{ position: "absolute", left: 0, color: c.primary }}>–</span>Group seminars structured so that AI use shows up immediately — fluent answers without specific knowledge of the text, polished prose without engagement with the particular reading.</li>
        <li style={{ padding: "5px 0 5px 22px", position: "relative", marginBottom: "4px" }}><span style={{ position: "absolute", left: 0, color: c.primary }}>–</span>Explicit instruction in using AI well: how to interrogate its output, when to trust it, when to push back, how to recognize fluent confidence without grounding.</li>
      </ul>
      <p style={s.p}>The frame that connects these: stop assigning work that AI can do. Start assigning practices that change the person doing them. The deliverable is no longer the point. It never really was.</p>
      <h3 style={s.h3}>The Social and Political Dimension</h3>
      <p style={s.p}>The humanities have always been partly concerned with how societies organize themselves, distribute power, and hold institutions accountable. AI intensifies those questions. <a href="#transform" style={{ color: c.primary, textDecoration: "none" }}>Section 4</a> develops the economic picture; <a href="#futures" style={{ color: c.primary, textDecoration: "none" }}>Section 6</a>'s Displacement and Concentration futures show what political stress looks like when labor shifts or gains concentrate. The question here is what educators do with that — helping students recognize they are already inside a political transition, and giving them tools to reason about it rather than only react.</p>
      <DQ questions={["What is a liberal arts education actually for? Has your answer changed in light of AI?", "If AI-driven productivity gains concentrate among a small number of actors, what political mechanisms exist to redistribute them — and are those mechanisms adequate?", "The section argues that large-scale economic disruption becomes political disruption. What historical examples support this? Where does the analogy break down?", "What would a social contract designed for an AI economy have to assume that the current one does not?", "Aesthetic judgment — the capacity to say 'this is good and this is not, and here is why' — is one of the capabilities AI handles least well. Is that a permanent condition? And what would be lost to us if it weren't?", "If a work passes every critical test but was made by AI, does the canon need to change — or does the test?", "A student submits a thoughtful, well-edited AI-generated paper. Another submits a clumsy, genuine attempt at the same argument. Which has gotten more from the assignment? Which has gotten more from their education?", "Where in your own field is the gap between 'having a document' and 'having an argument' most important — and is that gap itself at risk?"]} />
      <TryIt prompts={["Ask an AI to write the strongest possible argument that liberal arts education is obsolete in an AI-capable world. Then ask it to write the strongest argument for its continued relevance. Compare the quality and depth of both — and ask yourself which it produced more convincingly.", "Tell an AI your field, your students' likely career paths, and what you teach. Ask: 'Which parts of what I teach are most important to preserve in an AI-abundant world, and which should I reconceive entirely? Be direct and specific.'", "Ask an AI to design a single assignment for a college humanities course that it cannot meaningfully complete, but that requires students to use AI in the process. Evaluate whether what it proposes actually works — and whether it would have passed itself."]} />
    </div>
  );
}
