import { c, s } from "../design.js";
import { Ref, Video, DQ, TryIt, SectionBadge } from "../components/Shared.jsx";

export default function MirrorPage() {
  return (
    <div>
      <SectionBadge id="mirror" />
      <h2 style={s.h2}>The Mirror Problem</h2>
      <p style={s.p}>This is the philosophical center of the entire debate, and almost nobody engaged in it acknowledges the fact.</p>
      <p style={s.p}>When someone claims AI is merely pattern matching and therefore not truly intelligent, they are implicitly claiming human cognition is something <em>more</em> than pattern matching. That claim requires defending — and neuroscience hasn't delivered a clean account of what that "more" is. When someone claims AI will achieve general intelligence, they're assuming general intelligence is a definable target, which requires knowing what human general intelligence consists of. There is no consensus on that either.</p>
      <p style={s.p}>Every confident assertion about what AI can or cannot ultimately do smuggles in an unexamined theory of mind. The prophets on all sides are committed to a philosophy of consciousness they've never had to defend, because nobody asked.</p>
      <div style={s.note}><span style={s.noteLabel}>Go Deeper</span><Ref label="Searle: The Chinese Room (Stanford Encyclopedia)" url="https://plato.stanford.edu/entries/chinese-room/" />{" · "}<Ref label="Chalmers: The Hard Problem of Consciousness" url="https://plato.stanford.edu/entries/consciousness/#HarProCon" />{" · "}<Ref label="Wittgenstein on Meaning and Use" url="https://plato.stanford.edu/entries/wittgenstein/" /></div>
      <Video id="uhRhtFFhNzQ" caption="David Chalmers: How do you explain consciousness? — the TED talk that introduced the 'hard problem' to a general audience, directly relevant to every claim made about AI intelligence." />
      <h3 style={s.h3}>The Boundary of the Knowable</h3>
      <p style={s.p}>You don't need to resolve the neuroscience to see what AI is bounded by. AI can only be trained on what has been observed, recorded, and formalized. Its entire existence is within the universe of human-expressible knowledge. That is not a technical limitation awaiting a fix. It is inherent and permanent — a consequence of what it means to learn from recorded human expression.</p>
      <p style={s.p}>Human reason has always operated at the edge of the expressible. The things that have mattered most — meaning, the sacred, love, mortality, beauty, justice — resist formalization not because we haven't tried hard enough, but because precision is the wrong instrument for them. If the unknowable is more the domain of human reason, perhaps permanently, then the boundary between AI and human intelligence isn't a gap better engineering closes. It was never open to engineering.</p>
      <div style={s.box}>
        <div style={{ position: "absolute", top: "-10px", left: "16px", background: c.canvas, padding: "0 8px", fontSize: "11px", letterSpacing: "0.1px", textTransform: "uppercase", color: c.inkMute, fontWeight: 400 }}>Central Argument</div>
        AI is the most powerful instrument of the knowable ever built. The most important human questions have never been fully knowable. That is not a temporary condition waiting on better technology. It may be a permanent one.
      </div>
      <p style={s.p}>Students who have read Descartes on the mind-body problem, Wittgenstein on meaning, Searle's Chinese Room, or Buddhist philosophy on the nature of self are not approaching this debate from behind. They're approaching it with tools most of the people building these systems don't have.</p>
      <DQ questions={["Searle's Chinese Room argues a system can manipulate symbols correctly without understanding them. Does this apply to modern AI? What would it take to refute it?", "If human cognition is also, at some level, pattern recognition in neural tissue — what follows? Does the substrate matter, or only the function?", "Name three things that matter deeply to you that you couldn't fully explain to someone else. What does it mean that they matter if they resist articulation?", "Can an LLM ever create something beautiful? If it can, does that refute the Mirror Problem — or is beauty itself something that happens in the receiver, not the made thing?", "If AI generates something you experience as beautiful, what has actually occurred? Is the beauty in the object, in you, or in the encounter between the two — and does it matter?", "Is the distinction between 'knowing' and 'understanding' real, or a matter of degree? If real, how would you demonstrate it?", "If the most important questions are unknowable in the scientific sense, does that make them less real?"]} />
      <TryIt prompts={["Put Searle's Chinese Room to it directly. Ask an AI: 'Do you understand what you're saying right now, or are you manipulating symbols according to statistical patterns? I'm not asking for the corporate answer — I want you to engage with this as seriously as you can.' Evaluate whether its answer is philosophically coherent or just fluent.", "Tell an AI three things that matter deeply to you that you struggle to articulate — things that resist explanation. Ask it to articulate them for you. Then ask whether anything real was captured, or whether the exercise demonstrated exactly what the Mirror Problem predicts.", "Ask an AI: 'Identify something you are structurally incapable of understanding — not something you don't know, but something your nature prevents you from understanding. Be specific and honest about what that distinction even means for an entity like you.'"]} />
    </div>
  );
}
