import { c, s } from "../design.js";
import { Ref, Video, DQ, TryIt, SectionBadge } from "../components/Shared.jsx";

export default function MirrorPage() {
  return (
    <div>
      <SectionBadge id="mirror" />
      <h2 style={s.h2}>The Mirror Problem</h2>
      <p style={s.p}>This is the philosophical center of the entire debate, and almost nobody engaged in it acknowledges the fact.</p>
      <p style={s.p}>When someone claims AI is merely pattern matching and therefore not truly intelligent, they are implicitly claiming human cognition is something <em>more</em> than pattern matching. That claim requires defending — and neuroscience hasn't delivered a clean account of what that "more" is. When someone claims AI will achieve general intelligence, they're assuming general intelligence is a definable target, which requires knowing what human general intelligence consists of. There is no consensus on that either.</p>
      <p style={s.p}>Every confident assertion about what AI can or cannot ultimately do builds in an unexamined theory of mind. The prophets on all sides are committed to a philosophy of consciousness they've never had to defend, because nobody asked.</p>
      <p style={s.p}>If human brains are also, at some level, pattern systems, the dispute is not "patterns vs. something else." It is whether substrate matters — whether what it is like to grieve, or to be wrong in public, or to be changed by an idea, is the kind of thing a statistical model can have. Functionalists say yes in principle; others say testimony and transformation require a lived subject. The guide does not settle that. It insists you notice which side you are already on.</p>
      <div style={s.note}><span style={s.noteLabel}>Go Deeper</span><Ref label="Turing: Computing Machinery and Intelligence (1950)" url="https://academic.oup.com/mind/article/LIX/236/433/986238" />{" · "}<Ref label="Searle: Minds, Brains, and Programs (1980)" url="https://doi.org/10.1017/S0140525X00005756" />{" · "}<Ref label="Chalmers: Could a Large Language Model Be Conscious?" url="https://arxiv.org/abs/2303.07103" />{" · "}<Ref label="Searle: The Chinese Room (Stanford Encyclopedia)" url="https://plato.stanford.edu/entries/chinese-room/" />{" · "}<Ref label="Chalmers: The Hard Problem of Consciousness" url="https://plato.stanford.edu/entries/consciousness/#HarProCon" />{" · "}<Ref label="Wittgenstein on Meaning and Use" url="https://plato.stanford.edu/entries/wittgenstein/" /></div>
      <Video id="uhRhtFFhNzQ" caption="David Chalmers: How do you explain consciousness? — the TED talk that introduced the 'hard problem' to a general audience, directly relevant to every claim made about AI intelligence." />
      <h3 style={s.h3}>The Boundary of the Knowable</h3>
      <p style={s.p}>The argument above turns on what we don't know about cognition. The argument that follows is independent of it. Even if we resolved the neuroscience tomorrow, what AI is bounded by would not change.</p>
      <p style={s.p}>AI can only be trained on what has been observed, recorded, and formalized. Its entire existence is within the universe of human-expressible knowledge. That is not a technical limitation awaiting a fix. It is inherent and permanent — a consequence of what it means to learn from recorded human expression.</p>
      <p style={s.p}>Human reason has always operated at the edge of the expressible. The things that have mattered most — meaning, the sacred, love, mortality, beauty, grief, wonder — resist formalization not because we haven't tried hard enough, but because precision is the wrong instrument for them. If the unknowable is more the domain of human reason, perhaps permanently, then the boundary between AI and human intelligence isn't a gap better engineering closes. It was never open to engineering.</p>
      <div style={s.box}>
        <div style={{ position: "absolute", top: "-10px", left: "16px", background: c.canvas, padding: "0 8px", fontSize: "11px", letterSpacing: "0.1px", textTransform: "uppercase", color: c.inkMute, fontWeight: 400 }}>Central Argument</div>
        AI is the most powerful tool yet for everything humans can formalize and measure. The most important human questions have never fit that mold. That gap is not something better engineering will close. It may never close.
      </div>
      <p style={s.p}>This is the expressibility limit from <a href="#bad" style={{ color: c.primary, textDecoration: "none" }}>Section 3</a> — distinct from the testimony limit and from the open question about capability ceilings. A machine could outperform humans on every formal test and still not close the gap between what can be said and what is true. <a href="#unknown" style={{ color: c.primary, textDecoration: "none" }}>Section 8</a> asks whether scaling changes that picture technically; this section asks whether it changes it philosophically.</p>
      <p style={s.p}>Students who have read Descartes on the mind-body problem, Wittgenstein on meaning, Searle's Chinese Room, or Buddhist philosophy on the nature of self are not approaching this debate from behind. They're approaching it with tools most of the people building these systems don't have.</p>
      <div style={s.note}><span style={s.noteLabel}>From Theory to Practice →</span>The question of what AI fundamentally is — tool, agent, or something else entirely — is not only philosophical. It determines who you hold responsible when AI causes harm. <a href="#commission" style={{ color: c.primary, textDecoration: "none" }}>The AI Ethics Sim</a> puts that question to work: a government ethics commission, real cases, real decisions. What you've been thinking through here shapes every ruling you make there.</div>
      <DQ questions={["Searle's Chinese Room argues a system can manipulate symbols correctly without understanding them. Does this apply to modern AI? What would it take to refute it?", "If human and machine cognition are both pattern-based at some level, is testimony the remaining distinction — or is there none?", "Name three things that matter deeply to you that you couldn't fully explain to someone else. What does it mean that they matter if they resist articulation?", "If AI generates something you experience as beautiful, what has actually occurred? Is the beauty in the object, in you, or in the encounter between the two — and does it matter?", "Is the distinction between 'knowing' and 'understanding' real, or a matter of degree? If real, how would you demonstrate it?", "If the most important questions are unknowable in the scientific sense, does that make them less real?"]} />
      <TryIt prompts={["Put Searle's Chinese Room to it directly. Ask an AI: 'Do you understand what you're saying right now, or are you manipulating symbols according to statistical patterns? I'm not asking for the corporate answer — I want you to engage with this as seriously as you can.' Evaluate whether its answer is philosophically coherent or just fluent.", "Tell an AI three things that matter deeply to you that you struggle to articulate — things that resist explanation. Ask it to articulate them for you. Then ask whether anything real was captured, or whether the result matches what the Mirror Problem predicts.", "Ask an AI: 'Name something you are built in a way that prevents you from understanding — not something you don't know, but something your design rules out. Be specific about what that distinction means for a system like you.'"]} />
    </div>
  );
}
