import { s } from "../design.js";
import { Ref, Video, DQ, TryIt, SectionBadge } from "../components/Shared.jsx";

export default function TransformPage() {
  return (
    <div>
      <SectionBadge id="transform" />
      <h2 style={s.h2}>Where It Can Already Transform Society</h2>
      <p style={s.p}>Even at its current level — before any question of AGI — AI is powerful enough to inflect significant change in how humanity addresses its hardest problems. This is not speculation. It is already happening.</p>
      <h3 style={s.h3}>Medical and Scientific Research</h3>
      <p style={s.p}>AI's best fit is finding non-obvious patterns in vast bodies of existing data: genomics, drug interactions, imaging, literature reviews spanning thousands of papers no single researcher could read in a lifetime. The key distinction is that AI isn't being asked to assert truth — it surfaces candidates for human validation. That is a much better match for what these systems actually do.</p>
      <p style={s.p}>What would take researchers years of effort, or a fortunate accident of insight, AI can surface systematically. Accelerated drug discovery, earlier disease detection, connections across siloed research bodies — the quality of life implications are real.</p>
      <div style={s.note}><span style={s.noteLabel}>Go Deeper</span><Ref label="DeepMind AlphaFold: Solving the protein folding problem" url="https://deepmind.google/technologies/alphafold/" />{" · "}<Ref label="Nature: AI in drug discovery" url="https://www.nature.com/articles/s41573-019-0024-5" /></div>
      <Video id="Y48UmC3ODFk" caption="AlphaFold and the End of the Protein Folding Problem — a concrete example of AI doing something that would have taken humans decades." />
      <h3 style={s.h3}>Writing Software</h3>
      <p style={s.p}>Code is the most AI-compatible domain because it is objectively verifiable — it runs, or it doesn't. Software is also the most malleable material we have: it changes instantly, costs nothing to iterate, has no physical constraints. AI compresses the distance between having an idea and having a working prototype. People who could imagine things but lacked the means to build them now can. The more interesting question isn't which jobs disappear but what gets built that never would have been attempted.</p>
      <h3 style={s.h3}>Economic Impact: The Jobs Already at Risk</h3>
      <p style={s.p}>Every previous wave of automation displaced physical labor: the loom replaced the weaver, the tractor replaced the field hand, the assembly line replaced the craftsman. The new jobs that followed were, by and large, cognitive — requiring language, analysis, judgment. Those jobs were considered safe precisely because machines couldn't do them.</p>
      <p style={s.p}>AI breaks that pattern. The jobs most immediately at risk are not physical — they are cognitive, credentialed, and white-collar. Goldman Sachs estimated in 2023 that 300 million jobs globally are exposed to AI automation, with two-thirds of occupations having at least a quarter of their tasks automatable today. McKinsey's research suggests AI could technically automate up to 57% of US work hours. The most exposed roles include paralegal work, financial analysis, customer service, medical transcription, basic journalism, and entry-level software development — jobs that, a decade ago, were considered the safe destination for people displaced by factory automation.</p>
      <p style={s.p}>The optimistic counter-argument is that technology has always created more jobs than it destroyed — and historically, that has been true. The question is whether the speed and breadth of AI displacement will outpace the labor market's ability to adapt, and whether the new jobs it creates will be accessible to the people whose jobs it eliminates. A 55-year-old paralegal and a 22-year-old computer science graduate are not equivalently positioned to pivot.</p>
      <p style={s.p}>The more pointed question — especially for students in liberal arts fields — is whether the jobs that survive will be the ones that require exactly what a liberal arts education develops: original judgment, ethical reasoning, the ability to navigate ambiguity, and communication that actually moves people. That argument is available. It is also possibly self-serving, and worth examining with some rigor.</p>
      <div style={s.note}><span style={s.noteLabel}>Go Deeper</span><Ref label="Goldman Sachs: How AI Will Affect the US Labor Market" url="https://www.goldmansachs.com/insights/articles/how-will-ai-affect-the-us-labor-market" />{" · "}<Ref label="McKinsey: Generative AI and the Future of Work in America" url="https://www.mckinsey.com/mgi/our-research/generative-ai-and-the-future-of-work-in-america" /></div>
      <Video id="t1gLIc9ebiE" caption="MIT economist and Nobel laureate Daron Acemoglu on why America is unprepared for the economic storm caused by AI — a rigorous, skeptical counterpoint to the productivity optimists." />
      <h3 style={s.h3}>The Question That Determines the Magnitude</h3>
      <p style={s.p}>The transformations above are already underway — and they rest on AI doing what current systems do well: finding patterns, surfacing candidates, automating the legible. The scale of societal change from here depends almost entirely on one unresolved question: can AI equal or surpass human reason?</p>
      <p style={s.p}>If the answer is no — if today's capabilities are near their ceiling — then AI is a powerful tool that augments human work, much as previous technologies have. Significant change, but change within a recognizable world. If the answer is yes — if AI continues advancing at the pace of the last several years and eventually achieves general reasoning — then the nature of the change is categorically different. Not just more efficient humans, but a world in which the comparative advantage of being human is genuinely unclear.</p>
      <div style={s.pq}>The judgment students need to make isn't technical. It's philosophical: is human-level reasoning something a machine can achieve — and if it is, what does that mean for what humans are for?</div>
      <DQ questions={["AI surfaces patterns humans wouldn't find in a lifetime. Does a discovery made by AI carry the same weight as one made by a human researcher? Why or why not?", "Every prior wave of automation displaced physical labor and created cognitive jobs. AI displaces cognitive labor. What kind of jobs does it create — and who gets them?", "Goldman Sachs estimates 300 million jobs are exposed to AI automation. McKinsey says AI could automate 57% of US work hours. What's the difference between 'exposed to' and 'will be replaced by' — and does that distinction hold under sustained AI advancement?", "The section argues liberal arts skills may be exactly what survives automation — but notes this argument is possibly self-serving. Steelman the skeptical position: what if judgment and communication are also automatable?", "The section argues today's AI is already transformative but the magnitude of future change depends on whether it can match human reason. Do you find that framing convincing? What's missing from it?", "Has any previous technology created a moment where humans genuinely had to ask what they were for? What happened — and what does that suggest about now?"]} />
      <TryIt prompts={["Make it personal. Tell an AI your intended career or field. Ask: 'Give me an honest breakdown of which parts of this job are most exposed to AI automation in the next ten years, and what skills in this field will be hardest to automate. Don't be reassuring — be accurate.'", "Run the two-scenario simulation. Tell an AI what you studied, where you live, and what you plan to do. Ask: 'Walk me through what my career prospects might look like in 2032 under two assumptions: AI capabilities plateau at their current level, and AI continues advancing at the pace of the last five years. Be specific about my field.'", "Ask an AI to compare today's moment to one prior technological disruption — pick one it knows well. Ask it to argue both that the analogy holds and that it doesn't. The limits of the analogy are where the genuinely new territory begins."]} />
    </div>
  );
}
