import { c, s } from "../design.js";
import { Ref, DQ, TryIt, SectionBadge } from "../components/Shared.jsx";

export default function UnknownPage() {
  const items = [
    { title: "Whether the scaling laws hold", body: "AI progress over the last several years has tracked closely with the amount of compute and data thrown at it — a relationship formalized in papers by Kaplan and by Hoffmann (Chinchilla). If those scaling laws continue, predicting AI capability becomes a budget question. If they break — if returns diminish past a point — the entire trajectory of the field bends. We do not know which it will be, and the people most confident either way tend to be the ones who've staked their careers on a position." },
    { title: "Emergence — and whether it's real", body: "Capabilities keep appearing at scale that nobody predicted — translation, multi-step reasoning, coding ability — without being explicitly trained for. The Emergentist camp takes this seriously. The counter-argument (Schaeffer et al., 2023) is that what looks like emergence is partly an artifact of how we measure: smooth underlying improvement that appears as a sudden jump only because the metric is binary. Both could be partly right. We do not have a settled account.", link: { label: "Schaeffer et al.: Are Emergent Abilities a Mirage?", url: "https://arxiv.org/abs/2304.15004" } },
    { title: "Alignment", body: "Whether AI systems can be reliably made to do what we want them to do — especially as they grow more capable — is the central technical question of the safety field. We do not have a robust answer. Anthropic, OpenAI, and academic labs are working on it; the work is real; the result is uncertain. The Doomer position is that alignment is unsolvable on the current trajectory. The Safety Institutionalist position is that it is solvable with the right investment. Both are working from real uncertainty." },
    { title: "Interpretability", body: "We do not know how these systems work internally. We can describe their behavior. We can poke at their attention patterns. We are beginning to find interpretable circuits inside the largest models. But we cannot fully explain why a given output occurred or predict what an input will produce in advance. A technology that operates on cognition while remaining opaque to its operators is historically unusual. The consequences of that opacity, for safety and for trust, are not yet understood." },
    { title: "Agency", body: "AI acting in the world rather than generating text is early-stage and hard to predict. Agent systems — AI that browses, books, writes code, executes transactions, calls other agents — are crossing the threshold from demo to deployment now. The difference between a tool that generates and a tool that acts is not merely technical. It is the difference between a typewriter and an employee." },
    { title: "New architectures", body: "Chain-of-thought reasoning, reinforcement learning from feedback, multimodal training, world-models — any of these may shift the picture significantly. The field as it exists today is not the field that will exist in five years." },
    { title: "Societal feedback loops", body: "How does mass AI use change what humans know, practice, and choose to develop? If students stop practicing difficult writing because AI will do it, what happens to the capacity for difficult thinking? If lawyers stop drafting because AI drafts, what happens to legal reasoning twenty years from now? We are inside that experiment. Results not yet available." },
  ];
  return (
    <div>
      <SectionBadge id="unknown" />
      <h2 style={s.h2}>The Genuinely Unknown</h2>
      <p style={s.p}>Strong conclusions about AI's future run through a set of questions that are genuinely unresolved. These are not philosophical puzzles — they are live technical and empirical problems that block clear forecasts. How each one resolves shifts the picture significantly.</p>
      <p style={s.p}>If scaling laws break, the entire timeline of disruption shifts. If alignment fails, institutions that deploy AI at scale are making bets they cannot fully explain. If agentic systems act in the world, responsibility and liability change shape. If mass use changes what humans practice, education trains different minds than it did a decade ago. The relational side of that last feedback loop is developed in <a href="#students" style={{ color: c.primary, textDecoration: "none" }}>Section 10</a>.</p>
      {items.map((item, i) => (
        <div key={i} style={{ borderLeft: `3px solid ${c.hairline}`, paddingLeft: "18px", margin: "20px 0" }}>
          <div style={{ fontWeight: 500, marginBottom: "6px", color: c.ink, letterSpacing: "-0.1px" }}>{item.title}</div>
          <p style={{ ...s.p, fontSize: "15px", marginBottom: item.link ? "8px" : 0 }}>{item.body}</p>
          {item.link && <Ref label={item.link.label} url={item.link.url} />}
        </div>
      ))}
      <div style={s.note}><span style={s.noteLabel}>Go Deeper</span><Ref label="Kaplan et al.: Scaling Laws for Neural Language Models" url="https://arxiv.org/abs/2001.08361" />{" · "}<Ref label="NIST: AI Risk Management Framework" url="https://www.nist.gov/itl/ai-risk-management-framework" />{" · "}<Ref label="Christiano: What Failure Looks Like" url="https://www.alignmentforum.org/posts/HBxe6wdjxK239zajf/what-failure-looks-like" />{" · "}<Ref label="Chollet: On the Measure of Intelligence" url="https://arxiv.org/abs/1911.01547" />{" · "}<Ref label="Anthropic: Core Views on AI Safety" url="https://www.anthropic.com/research/core-views-on-ai-safety" /></div>
      <DQ questions={["What is the difference between a question that is unanswered and one that is unanswerable? Give examples from your field.", "The societal feedback loop question suggests AI use may change what we are capable of. What historical precedents exist for a technology changing human cognitive capacity?", "If AI can eventually produce outputs that are indistinguishable from great human art — indistinguishable to critics, to audiences, to time — what is actually lost? Is the loss in the experience, or in the act of making?", "If capabilities emerge in AI that nobody designed or predicted, what does that tell us about our ability to control the technology?", "How should one act under genuine uncertainty about high-stakes outcomes? What does your philosophical tradition say?"]} />
      <TryIt prompts={["Ask an AI: 'What is the most important thing you currently cannot do — and do you think that's a temporary limitation or a permanent one? Give your actual view, not a hedge.' Push back if it evades.", "Ask an AI to reason under uncertainty: 'You don't know whether you'll be significantly more capable in five years or essentially the same. Given that uncertainty, what should universities do differently right now — specifically, not in general terms?' Evaluate whether it can reason usefully when it can't resolve the question.", "Tell an AI about a technology that significantly changed how you think — something you use constantly that has altered what you know or how you process things. Ask it to extrapolate: if AI continues advancing for a decade and becomes a constant cognitive companion, what might you lose the capacity to do — and would that be a loss worth grieving?"]} />
    </div>
  );
}
