import { s } from "../design.js";
import { Ref, Video, DQ, TryIt, SectionBadge } from "../components/Shared.jsx";

export default function WhatPage() {
  return (
    <div>
      <SectionBadge id="what" />
      <h1 style={s.h2}>What It Actually Is Today</h1>
      <p style={s.p}>AI is pattern recognition at massive scale. Large language models are trained on human-generated text and predict plausible continuations of it — a compression of recorded human thought. The key claim that follows: AI reflects human knowledge back at us. As a first pass, it is a mirror more than a mind.</p>
      <p style={s.p}>That framing matters for the rest of this guide. It is also a position with assumptions, which Section 7 — The Mirror Problem — will examine. For now, treat it as a working frame you can use and revise.</p>
      <p style={s.p}>AGI — artificial general intelligence — has no agreed-upon definition. Some define it as a system that can reason across domains the way humans do. OpenAI uses a working definition closer to "outperforms humans at most economically valuable work." The disagreement is not incidental; it is part of why the debate is so confused. We do not have AGI by any definition. Whether we ever will is one of the open questions we'll come back to.</p>
      <p style={s.p}>Because it is primarily a mirror, today's AI mostly creates within the universe of what already exists. It recombines far more than it originates. It optimizes within a given framework; it does not ask why the framework exists. And because it is trained to produce plausible-sounding output, it is confident and fluent even when it is wrong. The most dangerous output is the one that sounds most authoritative. The qualifier "primarily" matters — the Emergentist camp (Section 5) argues that new capabilities keep appearing at scale that nobody designed for, and the evidence is real. We won't settle that here; we'll flag it and return to it.</p>
      <div style={s.note}><span style={s.noteLabel}>Go Deeper</span><Ref label="Anthropic: Constitutional AI" url="https://www.anthropic.com/research/constitutional-ai-harmlessness-from-ai-feedback" />{" · "}<Ref label="3Blue1Brown: Attention in transformers" url="https://www.youtube.com/watch?v=eMlx5fFNoYc" /></div>
      <Video id="wjZofJX0v4M" caption="3Blue1Brown: But what is a GPT? — visual walkthrough of how transformers predict the next token, and why that is not the same as understanding." />
      <DQ questions={["If AI is a compression of recorded human thought, what does it mean that most of human thought was never written down?", "What is the difference between predicting a plausible next word and understanding what a sentence means? Is there a difference that matters?", "'A mirror, not a mind' sounds clear — but what would you need to believe about minds for that distinction to hold?", "We say a thermostat 'knows' the room is cold. At what point does that way of speaking become misleading?", "Can an LLM ever create something beautiful? Does your answer require you to take a position on what beauty is and where it lives?"]} />
      <TryIt prompts={["Pick something that matters to you — a poem, a memory, a moral conviction. Ask an AI to explain what it means. Then write your own explanation. Compare them: where does the AI version diverge, and what does that gap tell you about the difference between fluency and understanding?", "Ask an AI: 'I want to understand what you actually are. Walk me through how you generate a response — not the press release version, the most accurate account you can give of your own mechanism. Then tell me where that account breaks down.' See whether it can describe its own limits plainly.", "Try the thermostat test at scale. Ask an AI: 'Do you know what you're saying right now, or are you predicting plausible tokens? I'm not asking for the safe answer — I want you to engage with the question seriously.' Note what it does when pushed."]} />
    </div>
  );
}
